import React from "react";
import { ScrollView, Text, View, Pressable } from "react-native";
import { C, outletOmzet, formatJt, styles } from "@/src/theme";
import { QuickArt } from "@/src/components/QuickIcons";
import { Icon } from "@/src/components/Icon";
import { Header } from "@/src/components/Header";

export function Analytics({ onBack }: any) {
  const bars = [28, 44, 31, 49, 65, 81, 100, 88, 69, 53, 36, 25, 18];
  const maxOmzet = Math.max(...outletOmzet.map((o) => o.value));
  return <View style={styles.flex}><Header title="Analisa" onBack={onBack} right={<Pressable style={styles.iconButton}><Icon name="ellipsis-horizontal" color="#fff" /></Pressable>} /><ScrollView contentContainerStyle={styles.page}><View style={styles.insight}><View style={styles.insightGlow} /><View style={styles.insightTop}><Text style={styles.insightLabel}>✦ INSIGHT HARI INI</Text><Icon name="sparkles-outline" color={C.teal} size={20} /></View><Text style={styles.insightText}>Omzet naik <Text style={{ color: C.teal }}>12%</Text> dibanding kemarin.</Text><Text style={styles.insightSub}>Jam ramai pukul 14.00–16.00 — pertimbangkan tambah stok di jam itu.</Text><Text style={styles.insightTime}>Diperbarui 06.00 tadi pagi</Text></View><View style={styles.stats}><Stat label="Total transaksi" value="128" art="transaksi" /><Stat label="Total omzet" value="Rp 4,1jt" art="wallet" /></View><View style={styles.chartCard}><View style={styles.sectionTitleRow}><Text style={styles.sectionTitle}>Jam ramai hari ini</Text><Text style={styles.muted}>08–20</Text></View><View style={styles.chart}>{bars.map((height, i) => <View key={i} style={styles.barSlot}><View style={[styles.bar, { height: `${height}%`, backgroundColor: i === 6 ? C.teal : "#C7F1E9" }]} /><Text style={styles.barLabel}>{8 + i}</Text></View>)}</View></View><View style={styles.topOutlet}><Text style={styles.sectionTitle}>Outlet paling ramai</Text><View style={styles.topRow}><QuickArt name="trophy" size={42} /><View style={styles.transactionMain}><Text style={styles.transactionOutlet}>Warkop Sejagat Meruyung</Text><Text style={styles.muted}>64 transaksi bulan ini</Text></View><Text style={styles.amount}>Rp 2,4jt</Text></View></View><View style={styles.compareCard}><Text style={styles.sectionTitle}>Perbandingan omzet outlet</Text><Text style={styles.muted}>Bulan ini</Text>{outletOmzet.map((o) => <View key={o.name} style={styles.compareRow}><View style={styles.compareTop}><Text style={styles.compareName}>{o.name.replace("Warkop Sejagat ", "")}</Text><Text style={styles.compareValue}>{formatJt(o.value)}</Text></View><View style={styles.compareTrack}><View style={[styles.compareFill, { width: `${(o.value / maxOmzet) * 100}%`, backgroundColor: o.color }]} /></View></View>)}</View></ScrollView></View>;
}
function Stat({ label, value, art }: any) { return <View style={styles.stat}><QuickArt name={art} size={40} /><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text><Text style={styles.statTrend}>↑ 12% <Text style={styles.muted}>vs kemarin</Text></Text></View>; }
