import React from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import { LinearGradient } from "expo-linear-gradient";
import { Image } from "expo-image";
import { C, HEADER_BG, LOGO, parseRp, formatRp, styles } from "@/src/theme";
import { QuickArt } from "@/src/components/QuickIcons";
import { Icon } from "@/src/components/Icon";
import { TransactionRow } from "@/src/components/TransactionRow";

export function Home({ selectedOutlet, onOutlet, hiddenBalance, onHide, onGo, onQris, onNotifications, notifCount, onTestPayment, transactions, onOpenLink }: any) {
  const todayTx = transactions.filter((t) => t.time.startsWith("Hari ini"));
  const todayOmzet = todayTx.filter((t) => t.status === "Berhasil").reduce((s, t) => s + parseRp(t.amount), 0);
  const actions = [{ art: "analisa", label: "Analisa", press: () => onGo("analisa") }, { art: "pegawai", label: "Pegawai", press: () => onGo("profil") }, { art: "laporan", label: "Laporan", press: () => onGo("riwayat") }, { art: "outlet", label: "Outlet Saya" }, { art: "notifikasi", label: "Notifikasi", press: onNotifications, badge: notifCount }, { art: "bantuan", label: "Bantuan" }];
  return <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.hero}><Image source={HEADER_BG} style={styles.heroBg} contentFit="cover" transition={200} /><View style={styles.heroContent}><Pressable testID="outlet-selector" onPress={onOutlet} style={styles.outletPill}><Icon name="storefront-outline" color={C.navy} size={17} /><Text style={styles.outletText}>{selectedOutlet}</Text><Icon name="chevron-down" color={C.navy} size={16} /></Pressable><Image source={{ uri: LOGO }} style={styles.logoImg} contentFit="contain" transition={200} /><Text style={styles.welcome}>Selamat pagi, Agus 👋</Text></View></View>
    <View style={styles.balanceCard}><View style={styles.goldBox}><View style={styles.goldHeader}><Text style={styles.goldLabel}>SALDO TOKO</Text><Pressable testID="toggle-balance" onPress={onHide}><Icon name={hiddenBalance ? "eye-off-outline" : "eye-outline"} color={C.navy} size={18} /></Pressable></View><Text style={styles.balance}>{hiddenBalance ? "Rp •••••••" : "Rp 3.202.000"}</Text><Text style={styles.balanceHint}>Siap dicairkan</Text></View><Pressable testID="withdraw-button" style={styles.withdraw}><View style={styles.withdrawCircle}><Icon name="arrow-down" color="#fff" size={18} /></View><Text style={styles.withdrawText}>Pencairan</Text></Pressable></View>
    <View style={styles.summaryCard}><View style={styles.summaryCol}><View style={styles.summaryIconWrap}><QuickArt name="wallet" size={30} /></View><View style={styles.summaryColMain}><Text style={styles.summaryLabel}>Omzet hari ini</Text><Text style={styles.summaryValue}>{formatRp(todayOmzet)}</Text></View></View><View style={styles.summaryDivider} /><View style={styles.summaryCol}><View style={styles.summaryIconWrap}><QuickArt name="transaksi" size={30} /></View><View style={styles.summaryColMain}><Text style={styles.summaryLabel}>Transaksi hari ini</Text><Text style={styles.summaryValue}>{todayTx.length}</Text></View></View></View><Pressable testID="test-payment-home" onPress={onTestPayment} style={({ pressed }) => [styles.testPayBtn, pressed && styles.pressed]}><View style={styles.testPayIcon}><Icon name="volume-high" color="#fff" size={18} /></View><View style={styles.transactionMain}><Text style={styles.testPayTitle}>Test pembayaran masuk</Text><Text style={styles.muted}>Putar suara notifikasi contoh</Text></View><Icon name="play-circle" color={C.teal} size={28} /></Pressable>
    <View style={styles.section}><View style={styles.sectionTitleRow}><Text style={styles.sectionTitle}>Akses cepat</Text></View><View style={styles.actionGrid}>{actions.map((a) => <Pressable testID={`quick-${a.label}`} key={a.label} onPress={a.press} style={({ pressed }) => [styles.action, pressed && styles.pressed]}><View style={styles.actionTile}><QuickArt name={a.art} size={40} />{a.badge ? <View style={styles.notifBadge}><Text style={styles.notifBadgeText}>{a.badge}</Text></View> : null}</View><Text style={styles.actionLabel}>{a.label}</Text></Pressable>)}</View></View>
    <View style={styles.section}><View style={styles.sectionTitleRow}><Text style={styles.sectionTitle}>Menu lainnya</Text></View><Pressable testID="menu-pengeluaran" onPress={() => onOpenLink("https://guskitchen-management-system.vercel.app/guskitchen_belanja_tag.html")} style={({ pressed }) => [styles.linkRow, pressed && styles.pressed]}><View style={[styles.linkIcon, { backgroundColor: "#FFF0CF" }]}><Icon name="receipt-outline" color="#C47B13" size={20} /></View><View style={styles.transactionMain}><Text style={styles.menuLabel}>Pencatatan Pengeluaran</Text><Text style={styles.muted}>Catat belanja & pengeluaran toko</Text></View><Icon name="open-outline" color={C.muted} size={18} /></Pressable><Pressable testID="menu-absensi" onPress={() => onOpenLink("https://absensi-ksm.vercel.app/")} style={({ pressed }) => [styles.linkRow, pressed && styles.pressed]}><View style={[styles.linkIcon, { backgroundColor: "#E4E8FF" }]}><Icon name="finger-print-outline" color="#4657B8" size={20} /></View><View style={styles.transactionMain}><Text style={styles.menuLabel}>Absensi Karyawan</Text><Text style={styles.muted}>Kelola kehadiran pegawai</Text></View><Icon name="open-outline" color={C.muted} size={18} /></Pressable><Pressable testID="menu-kalkulator" onPress={() => onOpenLink("https://portal-pelatihan-usaha-desa.vercel.app/kalkulator_biaya_marketplace.html")} style={({ pressed }) => [styles.linkRow, pressed && styles.pressed]}><View style={[styles.linkIcon, { backgroundColor: "#DCF6EF" }]}><Icon name="calculator-outline" color={C.teal} size={20} /></View><View style={styles.transactionMain}><Text style={styles.menuLabel}>Kalkulator Marketplace</Text><Text style={styles.muted}>Hitung biaya jualan di marketplace</Text></View><Icon name="open-outline" color={C.muted} size={18} /></Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.promoScroll}><Promo colors={["#16BFA0", "#0E907D"]} icon="flash-outline" title="Cairkan saldo kapan saja" sub="Proses instan ke rekening toko" /><Promo colors={[C.navy, C.navy2]} icon="trending-up-outline" title="Pantau performa toko" sub="Insight transaksi di Analisa" /><Promo colors={["#F8CB70", "#E9A440"]} icon="qr-code-outline" title="QRIS makin cepat" sub="Statis & dinamis satu tombol" /></ScrollView>
    <View style={styles.section}><View style={styles.sectionTitleRow}><Text style={styles.sectionTitle}>Transaksi terakhir</Text><Pressable testID="see-all" onPress={() => onGo("riwayat")}><Text style={styles.link}>Lihat semua</Text></Pressable></View>{transactions.slice(0, 3).map((t) => <TransactionRow item={t} key={t.id} />)}</View>
  </ScrollView>;
}
function Promo({ colors, icon, title, sub }: any) { return <LinearGradient colors={colors} style={styles.promo}><View style={styles.promoIcon}><Icon name={icon} color="#fff" size={21} /></View><Text style={styles.promoTitle}>{title}</Text><Text style={styles.promoSub}>{sub}</Text></LinearGradient>; }
