import React, { useState } from "react";
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { C, formatRp, styles } from "@/src/theme";
import { QuickArt } from "@/src/components/QuickIcons";
import { Icon } from "@/src/components/Icon";

export function QrisDynamicModal({ visible, onClose, outlet, onToast }: any) {
  const [amount, setAmount] = useState("");
  const [generated, setGenerated] = useState(false);
  React.useEffect(() => { if (!visible) { setAmount(""); setGenerated(false); } }, [visible]);
  const numeric = Number(amount || "0");
  const setAmt = (t: string) => setAmount(t.replace(/[^0-9]/g, ""));
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : "height"} style={styles.modalBackdrop}><ScrollView style={styles.sheet} contentContainerStyle={styles.sheetScroll} keyboardShouldPersistTaps="handled"><View style={styles.sheetHandle} /><View style={styles.sheetHeader}><View><Text style={styles.sheetTitle}>QRIS Dinamis</Text><Text style={styles.muted}>{generated ? "Tunjukkan QR ke pembeli" : "Masukkan nominal pembayaran"}</Text></View><Pressable testID="close-qris-dynamic" onPress={onClose} style={styles.close}><Icon name="close" color={C.navy} size={20} /></Pressable></View>{!generated ? <><View style={styles.dynAmountRow}><Text style={styles.dynRp}>Rp</Text><TextInput testID="dynamic-amount" value={numeric ? formatRp(numeric).replace("Rp ", "") : ""} onChangeText={setAmt} keyboardType="number-pad" placeholder="0" placeholderTextColor="#AAB1C8" style={styles.dynInput} /></View><View style={styles.dynChips}>{[10000, 20000, 50000, 100000].map((v) => <Pressable testID={`amount-${v}`} key={v} onPress={() => setAmount(String(v))} style={({ pressed }) => [styles.dynChip, pressed && styles.pressed]}><Text style={styles.dynChipText}>{formatRp(v)}</Text></Pressable>)}</View><Pressable testID="generate-qris" disabled={!numeric} onPress={() => setGenerated(true)} style={({ pressed }) => [styles.dynBtn, !numeric && styles.dynBtnDisabled, pressed && styles.pressed]}><Icon name="qr-code" color={C.navy} size={18} /><Text style={styles.dynBtnText}>Buat QR Pembayaran</Text></Pressable></> : <><View style={styles.printCard}><View style={styles.printBrandBar}><Text style={styles.printBrandText}>QRIS</Text><Text style={styles.printBrandSub}>QR CODE STANDAR PEMBAYARAN</Text></View><Text style={styles.printMerchant}>{outlet}</Text><Text style={styles.dynAmountDisplay}>{formatRp(numeric)}</Text><View style={styles.printQrBox}><QuickArt name="qris" size={170} /></View><Text style={styles.printHint}>Pindai & bayar sesuai nominal di atas</Text></View><Pressable testID="mark-paid" onPress={() => { onClose(); onToast(`Pembayaran ${formatRp(numeric)} diterima`); }} style={({ pressed }) => [styles.dynBtn, pressed && styles.pressed]}><Icon name="checkmark-circle" color={C.navy} size={18} /><Text style={styles.dynBtnText}>Tandai lunas</Text></Pressable><Pressable testID="change-amount" onPress={() => setGenerated(false)} style={styles.dynSecondaryBtn}><Text style={styles.dynSecondaryText}>Ubah nominal</Text></Pressable></>}</ScrollView></KeyboardAvoidingView></Modal>;
}
